### ISSUE TITLE
Alternative method of habit notation

### ISSUE THREAD

**Issue by WillPlatnick** [c6p/logseq-habit-tracker#1]
Hello,
I wanted to ask if you'd be open to an alternative method of looking for habits rather than nesting them under a habits block that doesn't work with formatting (headings).

What if instead of this opinionated nested block, we were able to tag each habit with something like #habit, so they could live anywhere in the document?

**Comment by c6p** [comment]
@someinternetguy since I'm tracking habits by `habit text`, to implement this format I'm planning to provide a habit template (regex). For your example (not final):
```
\d{2}:\d{2} {{habit}}
```
And 2 options:
* Parent marker: `Habits` - to nest under as it is now.
* Habit marker: `#habit` - you can put them anywhere in habit title, they will be stripped, tracking `pushups` and `drink water` habits. And if there is more than one instance on a given day, it will be counted.

If that is fine, just stay tuned, I will implement it when I find the time.

**Comment by someinternetguy** [comment]
@c6p that regex looks good to my novice eyes. It would be cool if you could make it a user customizable regex so everyone can use the format they like... Also, I think having a customizable habit tag like you [mentioned above](https://github.com/c6p/logseq-habit-tracker/issues/1#issuecomment-939331593) would be good too. Thanks for your response and work on this 🤩.

**Comment by someinternetguy** [comment]
Thanks again @c6p! I finally had some time to test it out this evening, and it works a charm... :)
